name = "    踏雪补丁"
version = "3.81.2"
description = "踏雪mod补丁\n" .. version
author = "Death"
forumthread = ""
api_version = 6
priority = -3123

dst_compatible = false
dont_starve_compatible = true
reign_of_giants_compatible = true
shipwrecked_compatible = true
hamlet_compatible = true

icon_atlas = "modicon.xml"
icon = "modicon.tex"
configuration_options = {}
--[[ configuration_options = {
    {
        name = "PATCH_ENABLE",
        label = "补丁启用",
        hover = "关闭补丁前请禁用此选项加载一次",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "MD5_BYTES",
        label = "md5读取长度",
        hover = "md5计算时每次读取的字节长度,如果加载mod时内存溢出,可以尝试将此配置改小,如果禁用,请确保补丁版本匹配,并且踏雪文件没有被改动",
        options = {
            { description = "C语言库", data = "C" },
            { description = "32", data = 32 },
            { description = "16", data = 16 },
            { description = "8", data = 8 },
            { description = "1", data = 1 },
            { description = "1/16", data = 1 / 16 },
            { description = "禁用", data = false },
        },
        default = "C",
    },
    {
        name = "INGAMEGC",
        label = "内存清理",
        hover = "定时清理内存,设置清理检查间隔",
        options = {
            { description = "1分钟", data = 1 },
            { description = "5分钟", data = 5 },
            { description = "10分钟", data = 10 },
            { description = "30分钟", data = 30 },
            { description = "60分钟", data = 60 },
            { description = "禁用", data = false },
        },
        default = "10",
    },
    {
        name = "TAXUE_FIX",
        label = "踏雪优化",
        hover = "优化部分踏雪功能",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "TELEPORT_CAT",
        label = "定位猫猫",
        hover = "强制检查猫猫地灯会传送到猫猫地灯位置",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "FILLABLE",
        label = "一键使用",
        hover = "利息券,战利品券一键使用",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "DSC_COLOR",
        label = "文字颜色",
        hover = "物品上方显示或信息面板的文字颜色",
        options = {
            { description = "海蓝宝石色", data = { 127, 255, 212 } },
            { description = "品红色", data = { 255, 108, 180 } },
            { description = "青色", data = { 0, 255, 255 } },
            { description = "蓝色", data = { 0, 0, 255 } },
            { description = "绿色", data = { 0, 255, 0 } },
            { description = "黄色", data = { 255, 255, 0 } },
            { description = "金色", data = { 255, 215, 0 } },
            { description = "橙色", data = { 255, 165, 0 } },
            { description = "粉红色", data = { 255, 20, 147 } },
            { description = "浅绿色", data = { 144, 238, 144 } },
        },
        default = { 127, 255, 212 },
    },
    {
        name = "EXP_BANNER",
        label = "获得经验提示",
        hover = "使用信息面板显示获得经验提示",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "BANNER_COLOR",
        label = "经验提示颜色",
        hover = "经验提示的文字颜色",
        options = {
            { description = "海蓝宝石色", data = { 127, 255, 212 } },
            { description = "品红色", data = { 255, 108, 180 } },
            { description = "青色", data = { 0, 255, 255 } },
            { description = "蓝色", data = { 0, 0, 255 } },
            { description = "绿色", data = { 0, 255, 0 } },
            { description = "黄色", data = { 255, 255, 0 } },
            { description = "金色", data = { 255, 215, 0 } },
            { description = "橙色", data = { 255, 165, 0 } },
            { description = "粉红色", data = { 255, 20, 147 } },
            { description = "浅绿色", data = { 144, 238, 144 } },
        },
        default = { 255, 215, 0 },
    },
    {
        name = "DORP_ASH",
        label = "移除掉落物变灰烬",
        hover = "让着火的怪物掉落物不会变成灰烬",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "FORTUNE_PATCH",
        label = "梅运券使用方式修改",
        hover = "读劵时会将劵填装到玩家上,当填装的劵大于0,可以将鼠标放在右上角状态栏查看运势",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "FORTUNE_NUM",
        label = "梅运券显示数值",
        hover = "读劵的时候显示霉运值",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "CHEST_CAN_HAMMER",
        label = "可以锤迷你箱",
        hover = "让迷你箱子可以锤",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "PACKAGE_STAFF",
        label = "打包机防破坏",
        hover = "让打包机只能被黄金法杖摧毁",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "DISABLE_GEM_SAVE",
        label = "禁止宝石自动保存",
        hover = "移除使用宝石时的保存",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "BUFF_STAFF",
        label = "增强湛青法杖",
        hover = "提高湛青,锻造法杖的工作效率,并且提高加速数值",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "BUFF_STAFF_SPEED",
        label = "湛青增强速度",
        hover = "湛青/锻造法杖提高的速度",
        options = {
            { description = "20%(默认)", data = 0.2 },
            { description = "35%", data = 0.35 },
            { description = "50%", data = 0.5 },
            { description = "75%", data = 0.75 },
            { description = "100%", data = 1 },
            { description = "150%", data = 1.5 },
            { description = "300%", data = 3 },
        },
        default = 0.2,
    },
    {
        name = "COLOURFUL_STAFF_SPEED",
        label = "五彩增强速度",
        hover = "五彩法杖提高的速度",
        options = {
            { description = "20%", data = 0.2 },
            { description = "35%(默认)", data = 0.35 },
            { description = "50%", data = 0.5 },
            { description = "75%", data = 0.75 },
            { description = "100%", data = 1 },
            { description = "150%", data = 1.5 },
            { description = "300%", data = 3 },
        },
        default = 0.35,
    },
    {
        name = "BUFF_STAFF_MULT",
        label = "增强效率",
        hover = "湛青/锻造法杖提高的工作效率",
        options = {
            { description = "1.33/2(默认)", data = 1 },
            { description = "2/4", data = 2 },
            { description = "3/6", data = 3 },
            { description = "4/8", data = 4 },
            { description = "5/10", data = 5 },
            { description = "6/12", data = 6 },
        },
        default = 1,
    },
    {
        name = "GREEN_AMULET",
        label = "超级绿护符次数",
        hover = "修改超级建造护符添加绿宝石增加的耐久",
        options = {
            { description = "禁用", data = 4 },
            { description = "5", data = 5 },
            { description = "6", data = 6 },
            { description = "7", data = 7 },
            { description = "8", data = 8 },
            { description = "10", data = 10 },
        },
        default = 4,
    },
    {
        name = "SHOW_SHOP",
        label = "显示商店",
        hover = "显示商店售卖物品",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "SELL_PAVILION",
        label = "修改售货亭",
        hover = "金砖模式会在卖出后梅币大于500时,将售货亭内梅币转换为金砖,代替银行模式会同时拥有银行的功能",
        options = {
            { description = "禁用", data = false },
            { description = "金砖", data = "goldBrick" },
            { description = "银行", data = "bank" },
        },
        default = "goldBrick",
    },
    {
        name = "PACKAGE_PATCH",
        label = "修改打包系统",
        hover = "你值得拥有",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "OPEN_TREASURES",
        label = "打包开宝藏",
        hover = "打包书和打包机打包时会开宝藏,并将物品包进包裹",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "MACHINE_TREASURES",
        label = "打包机能否开宝藏",
        hover = "打包机能否打包宝藏",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = false,
    },
    {
        name = "DESTORY_CHEST",
        label = "打包拆宝藏箱",
        hover = "打包书和打包机开宝藏时,会将箱子一并拆除,并将物品包进包裹",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "DESTORY_STATUE",
        label = "打包拆宝藏雕像",
        hover = "打包书和打包机开宝藏时,会将雕像一并拆除,并将物品包进包裹",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "PACKAGE_MAX_AMOUNT",
        label = "每包最大数量",
        hover = "拆包时,重新打包不可堆叠物品的每包最大数量",
        options = {
            { description = "16",  data = 16 },
            { description = "32",  data = 32 },
            { description = "48",  data = 48 },
            { description = "64",  data = 64 },
            { description = "80",  data = 80 },
            { description = "100", data = 100 },
        },
        default = 16,
    },
    {
        name = "HIGH_EQUIPMENT_PERCENT",
        label = "高属性五彩比值",
        hover = "设定打包时判断高属性五彩装备的 (属性/能掉落的最大属性) 比值",
        options = {
            { description = "25%", data = 0.25 },
            { description = "50%", data = 0.50 },
            { description = "75%", data = 0.75 },
            { description = "85%", data = 0.85 },
            { description = "90%", data = 0.90 },
            { description = "95%", data = 0.95 },
        },
        default = 0.75,
    },
    {
        name = "PACKAGE_DES_MAX_LINES",
        label = "包裹最大行数",
        hover = "超级包裹显示最大行数",
        options = {
            { description = "0",  data = 0 },
            { description = "1",  data = 1 },
            { description = "3",  data = 3 },
            { description = "5",  data = 5 },
            { description = "10", data = 10 },
            { description = "15", data = 15 },
            { description = "20", data = 20 },
        },
        default = 10,
    },
    {
        name = "BETTER_DORP",
        label = "优化物品掉落",
        hover = "掉落物合并,当附近有开启的打包机时,直接进打包机",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "STACK_DROP",
        label = "掉落物是否合并",
        hover = "掉落物是否合并",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "FLOWERPOT_PHYSICS",
        label = "移除花盆碰撞",
        hover = "移除花盆碰撞",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "AUTO_AMULET",
        label = "终极自动护符",
        hover = "终极自动护符",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "AUTO_AMULET_WEAPON",
        label = "武器耐久触发值",
        hover = "当武器耐久低于此百分比时自动维修",
        options = {
            { description = "10%", data = 0.10 },
            { description = "20%", data = 0.20 },
            { description = "30%", data = 0.30 },
            { description = "40%", data = 0.40 },
            { description = "50%", data = 0.50 },
            { description = "60%", data = 0.60 },
            { description = "70%", data = 0.70 },
            { description = "80%", data = 0.80 },
            { description = "90%", data = 0.90 },
            { description = "100%", data = 1.00 },
            { description = "禁用", data = false },
        },
        default = 0.5,
    },
    {
        name = "AUTO_AMULET_ARMOR",
        label = "护甲触发值",
        hover = "当护甲耐久低于此百分比时自动维修",
        options = {
            { description = "10%", data = 0.10 },
            { description = "20%", data = 0.20 },
            { description = "30%", data = 0.30 },
            { description = "40%", data = 0.40 },
            { description = "50%", data = 0.50 },
            { description = "60%", data = 0.60 },
            { description = "70%", data = 0.70 },
            { description = "80%", data = 0.80 },
            { description = "90%", data = 0.90 },
            { description = "100%", data = 1.00 },
            { description = "禁用", data = false },
        },
        default = 0.7,
    },
    {
        name = "AUTO_AMULET_HEAL",
        label = "护符自动喝血",
        hover = "终极自动护符自动喝血量药剂",
        options = {
            { description = "启用", data = true },
            { description = "禁用", data = false },
        },
        default = true,
    },
    {
        name = "AUTO_AMULET_HEAL_KEY",
        label = "自动喝血按键",
        hover = "终极自动护符禁用自动喝血按键",
        options = {
            { description = "小键盘0", data = 256 },
            { description = "小键盘1", data = 257 },
            { description = "小键盘2", data = 258 },
            { description = "小键盘3", data = 259 },
            { description = "小键盘4", data = 260 },
            { description = "小键盘5", data = 261 },
            { description = "小键盘6", data = 262 },
            { description = "小键盘7", data = 263 },
            { description = "小键盘8", data = 264 },
            { description = "小键盘9", data = 265 },
            { description = "小键盘.", data = KEY_KP_PERIOD },
            { description = "小键盘/", data = KEY_KP_DIVIDE },
            { description = "小键盘*", data = KEY_KP_MULTIPLY },
            { description = "小键盘-", data = KEY_KP_MINUS },
            { description = "小键盘+", data = KEY_KP_PLUS },
            { description = "小键盘Enter", data = KEY_KP_ENTER },
        },
        default = 256,
    },
    {
        name = "AUTO_AMULET_HEAL_NUM",
        label = "自动喝血触发值",
        hover = "当血量低于此值时自动使用血量药剂",
        options = {
            { description = "10", data = 10 },
            { description = "20", data = 20 },
            { description = "30", data = 30 },
            { description = "40", data = 40 },
            { description = "50", data = 50 },
            { description = "60", data = 60 },
            { description = "70", data = 70 },
            { description = "80", data = 80 },
            { description = "90", data = 90 },
            { description = "100", data = 100 },
            { description = "禁用", data = false },
        },
        default = 30,
    },
    {
        name = "AUTO_AMULET_HEAL_PER",
        label = "自动喝血触发百分比",
        hover = "当血量低于此百分比时自动使用血量药剂",
        options = {
            { description = "10%", data = 0.10 },
            { description = "20%", data = 0.20 },
            { description = "30%", data = 0.30 },
            { description = "40%", data = 0.40 },
            { description = "50%", data = 0.50 },
            { description = "60%", data = 0.60 },
            { description = "70%", data = 0.70 },
            { description = "80%", data = 0.80 },
            { description = "90%", data = 0.90 },
            { description = "100%", data = 1.00 },
            { description = "禁用", data = false },
        },
        default = 0.5,
    },
} ]]